### ISSUE TITLE
[Feature request] Local storage alternative to self-hosting server

### ISSUE THREAD

**Issue by e-t-l** [ReceiptManager/Application#31]
How feasible would it be to add an option to the client app to save everything to local storage (or cloud storage, e.g. OneDrive) rather than to a self-hosted server? 

For many users, self-hosting adds a number of challenges, both in terms of computer literacy and hardware investment. Unless the server requires significant processing and/or storage space, it seems like many users would have the room to store their receipts on-device. If they want to access their receipts from another device or have it otherwise centralized, there could be an option to sync to 3rd-party cloud servers (or even just sync across devices with Syncthing).

Thoughts?

**Comment by monolidth** [comment]
Well, you will always need the receipt parser server if you want to use OCR but you could use my API server, I could give you free access but the images are stored on my server.
