### ISSUE TITLE
For IOS?

### ISSUE THREAD

**Issue by AjayShanker-geek** [ReceiptManager/Application#7]
Hi, I am interest in this project and I would like to know when will the IOS flutter app will be release?

**Comment by monolidth** [comment]
Hi, the application is completly written in flutter. Which means, that you can build the ios application if you have an mac thus I don't.

I take a look on  MAC VM like https://codemagic.io/start/.

Regards,
William

**Comment by monolidth** [comment]
![image](https://user-images.githubusercontent.com/71930307/100342463-4e6ddc80-2fde-11eb-9fa5-548673767aa3.png)

**Comment by monolidth** [comment]
Looks like there is an issue with the current (_used_) camera module.
https://github.com/flutter/flutter/issues/54599

However, if you have a **mac** use the following.
1. Install flutter dependencies
2. Run `flutter build ios`

Share any error with me.

I setup the IOS build server. However, I have the same error as previously shown.
![image](https://user-images.githubusercontent.com/71930307/100351689-21282b00-2fec-11eb-9bdc-3b24e3075a99.png)

Regards,
William

**Comment by AjayShanker-geek** [comment]
I have a Macbook Pro and I do program flutter app on my free time! 

I was wondering if I could download it from app store?

**Comment by monolidth** [comment]
The short answer is no. I currently can't build the IOS application, therefore I can't release the application in the app store. Thus, you can build the IOS application if you want?

Regards,
William

**Comment by AjayShanker-geek** [comment]
Sure! Once I am done with my app, I will move on to this project to help out.

Sorry man, I'm a student and new to github so I'm  learning along the way.

**Comment by monolidth** [comment]
I build the IOS application successfully. Cheers !
